.TH "Faculty" 3 "Вт 28 Мар 2023" "Version 1.0.0" "Accounting-of-scientific-activity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Faculty
.SH SYNOPSIS
.br
.PP
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "\fB$table\fP = '\fBFaculty\fP'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Модель сущности Кафедра\&.
.PP
Описывает поля и методы используемые для хранения и управления данными о факультете 
.PP
См\&. определение в файле \fBFaculty\&.php\fP строка \fB14\fP
.SH "Поля"
.PP 
.SS "$table = '\fBFaculty\fP'\fC [protected]\fP"

.PP
См\&. определение в файле \fBFaculty\&.php\fP строка \fB21\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Accounting-of-scientific-activity из исходного текста\&.
