.TH "DepartmentController" 3 "Вт 28 Мар 2023" "Version 1.0.0" "Accounting-of-scientific-activity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DepartmentController
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (Request $request)"
.br
.ti -1c
.RI "\fBedit\fP (\fBDepartment\fP $department)"
.br
.ti -1c
.RI "\fBupdate\fP (\fBDepartment\fP $department)"
.br
.ti -1c
.RI "\fBdestroy\fP (\fBDepartment\fP $department)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Контроллер сущности Кафедра\&.
.PP
Это класс контроллер сущности Кафедра, он отвечает за обработку запросов связанных с изменением данных в таблице Кафедра\&. 
.PP
См\&. определение в файле \fBDepartmentController\&.php\fP строка \fB14\fP
.SH "Методы"
.PP 
.SS "create ()"
Выводит форму для создания новой кафедры
.PP
\fBВозвращает\fP
.RS 4
Response 
.RE
.PP

.PP
См\&. определение в файле \fBDepartmentController\&.php\fP строка \fB32\fP
.SS "destroy (\fBDepartment\fP $department)"
Удаляет данные о кафедре из БД
.PP
\fBАргументы\fP
.RS 4
\fI$department\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
void 
.RE
.PP

.PP
См\&. определение в файле \fBDepartmentController\&.php\fP строка \fB76\fP
.SS "edit (\fBDepartment\fP $department)"
Показывает форму редактирования рессурса
.PP
\fBАргументы\fP
.RS 4
\fI$department\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
Response 
.RE
.PP

.PP
См\&. определение в файле \fBDepartmentController\&.php\fP строка \fB54\fP
.SS "index ()"
Выводит список кафедр\&.
.PP
\fBВозвращает\fP
.RS 4
\\Illuminate\\Http\\Response 
.RE
.PP

.PP
См\&. определение в файле \fBDepartmentController\&.php\fP строка \fB21\fP
.SS "store (Request $request)"
Сохраняет новую кафедру в БД\&.
.PP
\fBАргументы\fP
.RS 4
\fI$request\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
Response 
.RE
.PP

.PP
См\&. определение в файле \fBDepartmentController\&.php\fP строка \fB43\fP
.SS "update (\fBDepartment\fP $department)"
Изменяет данные о кафедре в БД\&.
.PP
\fBАргументы\fP
.RS 4
\fI$department\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
void 
.RE
.PP

.PP
См\&. определение в файле \fBDepartmentController\&.php\fP строка \fB65\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Accounting-of-scientific-activity из исходного текста\&.
