.TH "Type_publications" 3 "Вт 28 Мар 2023" "Version 1.0.0" "Accounting-of-scientific-activity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type_publications
.SH SYNOPSIS
.br
.PP
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "\fB$table\fP = '\fBType_publications\fP'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Типы публикаций
.PP
Класс описывает сущность типа публикации\&.
.PP
\fBАвтор\fP
.RS 4
Kovalenko Alexander ilondontami@gmail.com 
.RE
.PP
\fBВерсия\fP
.RS 4
1\&.0\&.0 
.RE
.PP

.PP
См\&. определение в файле \fBType_publications\&.php\fP строка \fB14\fP
.SH "Поля"
.PP 
.SS "$table = '\fBType_publications\fP'\fC [protected]\fP"

.PP
См\&. определение в файле \fBType_publications\&.php\fP строка \fB21\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Accounting-of-scientific-activity из исходного текста\&.
