.TH "Lecturer" 3 "Вт 28 Мар 2023" "Version 1.0.0" "Accounting-of-scientific-activity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lecturer
.SH SYNOPSIS
.br
.PP
.SS "Защищенные данные"

.in +1c
.ti -1c
.RI "\fB$table\fP = '\fBLecturer\fP'"
.br
.in -1c
.SH "Подробное описание"
.PP 
Модель сущности Преподаватель\&.
.PP
Описывает поля и методы используемые для хранения и управления данными о преподавателе\&. 
.PP
См\&. определение в файле \fBLecturer\&.php\fP строка \fB12\fP
.SH "Поля"
.PP 
.SS "$table = '\fBLecturer\fP'\fC [protected]\fP"

.PP
См\&. определение в файле \fBLecturer\&.php\fP строка \fB19\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Accounting-of-scientific-activity из исходного текста\&.
