.TH "Type_publicationsController" 3 "Вт 28 Мар 2023" "Version 1.0.0" "Accounting-of-scientific-activity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type_publicationsController
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (\fBType_publications\fP $type_publications)"
.br
.ti -1c
.RI "\fBedit\fP (\fBType_publications\fP $type_publications)"
.br
.ti -1c
.RI "\fBupdate\fP (\fBType_publications\fP $type_publications)"
.br
.ti -1c
.RI "\fBdestroy\fP (\fBType_publications\fP $type_publications)"
.br
.in -1c
.SH "Подробное описание"
.PP 
См\&. определение в файле \fBType_publicationsController\&.php\fP строка \fB7\fP
.SH "Методы"
.PP 
.SS "create ()"

.PP
См\&. определение в файле \fBType_publicationsController\&.php\fP строка \fB14\fP
.SS "destroy (\fBType_publications\fP $type_publications)"

.PP
См\&. определение в файле \fBType_publicationsController\&.php\fP строка \fB34\fP
.SS "edit (\fBType_publications\fP $type_publications)"

.PP
См\&. определение в файле \fBType_publicationsController\&.php\fP строка \fB24\fP
.SS "index ()"

.PP
См\&. определение в файле \fBType_publicationsController\&.php\fP строка \fB9\fP
.SS "store (\fBType_publications\fP $type_publications)"

.PP
См\&. определение в файле \fBType_publicationsController\&.php\fP строка \fB19\fP
.SS "update (\fBType_publications\fP $type_publications)"

.PP
См\&. определение в файле \fBType_publicationsController\&.php\fP строка \fB29\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Accounting-of-scientific-activity из исходного текста\&.
