.TH "LecturerController" 3 "Вт 28 Мар 2023" "Version 1.0.0" "Accounting-of-scientific-activity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LecturerController
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBindex\fP ()"
.br
.ti -1c
.RI "\fBcreate\fP ()"
.br
.ti -1c
.RI "\fBstore\fP (\fBLecturer\fP $lecturer)"
.br
.ti -1c
.RI "\fBedit\fP (\fBLecturer\fP $lecturer)"
.br
.ti -1c
.RI "\fBupdate\fP (\fBLecturer\fP $lecturer)"
.br
.ti -1c
.RI "\fBdestroy\fP (\fBLecturer\fP $lecturer)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Контроллер сущности Преподаватель\&.
.PP
Это класс контроллер сущности Перподаватель, он отвечает за обработку запросов связанных с изменением данных в таблице Преподаватель\&. 
.PP
См\&. определение в файле \fBLecturerController\&.php\fP строка \fB14\fP
.SH "Методы"
.PP 
.SS "create ()"
Выводит форму для создания записи о новом преподавателе
.PP
\fBВозвращает\fP
.RS 4
Response 
.RE
.PP

.PP
См\&. определение в файле \fBLecturerController\&.php\fP строка \fB32\fP
.SS "destroy (\fBLecturer\fP $lecturer)"
Удаляет данные о преподавателе из БД
.PP
\fBАргументы\fP
.RS 4
\fI$department\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
void 
.RE
.PP

.PP
См\&. определение в файле \fBLecturerController\&.php\fP строка \fB76\fP
.SS "edit (\fBLecturer\fP $lecturer)"
Показывает форму редактирования записи преподавателе
.PP
\fBАргументы\fP
.RS 4
\fI$department\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
Response 
.RE
.PP

.PP
См\&. определение в файле \fBLecturerController\&.php\fP строка \fB54\fP
.SS "index ()"
Выводит список преподавателей\&.
.PP
\fBВозвращает\fP
.RS 4
\\Illuminate\\Http\\Response 
.RE
.PP

.PP
См\&. определение в файле \fBLecturerController\&.php\fP строка \fB22\fP
.SS "store (\fBLecturer\fP $lecturer)"
Сохраняет запись о новом преподавателе в БД\&.
.PP
\fBАргументы\fP
.RS 4
\fI$request\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
Response 
.RE
.PP

.PP
См\&. определение в файле \fBLecturerController\&.php\fP строка \fB43\fP
.SS "update (\fBLecturer\fP $lecturer)"
Изменяет данные о преподавателе в БД\&.
.PP
\fBАргументы\fP
.RS 4
\fI$department\fP 
.RE
.PP
\fBВозвращает\fP
.RS 4
void 
.RE
.PP

.PP
См\&. определение в файле \fBLecturerController\&.php\fP строка \fB65\fP

.SH "Автор"
.PP 
Автоматически создано Doxygen для Accounting-of-scientific-activity из исходного текста\&.
